// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYflXthhumBT0QA9HROJLOELC6_oROWUg',
    appId: '1:248358115266:web:15ea8c87115abde7e1685b',
    messagingSenderId: '248358115266',
    projectId: 'roamsg-f92ce',
    authDomain: 'roamsg-f92ce.firebaseapp.com',
    storageBucket: 'roamsg-f92ce.firebasestorage.app',
    measurementId: 'G-JPK3K7NEFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL4LBanWWkrIdOdrARZkeTnR3FJLtS3Jk',
    appId: '1:248358115266:android:b444b85f69756a0ee1685b',
    messagingSenderId: '248358115266',
    projectId: 'roamsg-f92ce',
    storageBucket: 'roamsg-f92ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVa-eRZhEQjMNDA_HW1DbAzCnvNq5TqE0',
    appId: '1:248358115266:ios:fe925097d0784868e1685b',
    messagingSenderId: '248358115266',
    projectId: 'roamsg-f92ce',
    storageBucket: 'roamsg-f92ce.firebasestorage.app',
    iosBundleId: 'com.example.roamsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVa-eRZhEQjMNDA_HW1DbAzCnvNq5TqE0',
    appId: '1:248358115266:ios:fe925097d0784868e1685b',
    messagingSenderId: '248358115266',
    projectId: 'roamsg-f92ce',
    storageBucket: 'roamsg-f92ce.firebasestorage.app',
    iosBundleId: 'com.example.roamsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYflXthhumBT0QA9HROJLOELC6_oROWUg',
    appId: '1:248358115266:web:1a890d9034d40ecee1685b',
    messagingSenderId: '248358115266',
    projectId: 'roamsg-f92ce',
    authDomain: 'roamsg-f92ce.firebaseapp.com',
    storageBucket: 'roamsg-f92ce.firebasestorage.app',
    measurementId: 'G-Q2CM9RGRBG',
  );
}
